### ISSUE TITLE
Hello World using ELVM 8cc

### ISSUE THREAD

**Issue by Pebaz** [yabits/ebcvm#46]
Could a simple C program using ELVM 8cc be put into the README that shows how to call the `EFI_SYSTEM_TABLE.ConOut.OutputString()` function?

**Comment by retrage** [comment]
If you want to output a string from ELVM 8cc, you can use the `printf()`  as ELVM provides a small subset of libc. You can find how to compile C source code to EBC with ELVM by reading the test log of the EBC backend, but I'm unwilling to put the how-to in the README by myself because it is the general usage ELVM and should be out of the scope of the document.

Strictly speaking, directly calling a UEFI-provided function from the EBC backend is not possible. ELVM uses ELVM IR, a set of a small number of the primitive VM instructions, and its supported I/O is `PUTC` and `GETC` only. The EBC backend converts these IRs to the EFI function calls.

**Comment by Pebaz** [comment]
Thank you very much! 😃
